### ISSUE TITLE
Show music cover ?

### ISSUE THREAD

**Issue by osu** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#4]
Would be nice to have the music image shown on the RPC and only and remove the long TIDAL text and replace it by the song title, like spotify does

**Comment by purpl3F0x** [comment]
That's not possible by the Discord RPC API.
You can only have a limited amount of assets.
Spotify has some sort of deal with discord, even the images are from Spotify CDN and not Discords.

Same goes for the name. The name is set and only one per app id.

Closing the issue.

**Comment by Pavel-Sushko** [comment]
So is the issue Tidal side or Discord side? Basically to have it update the image you'd need to unregister and then reregister the RPC? Am I understanding properly? I imagine that's probably a taxing process. Wonder if there's a way to bypass that? If Spotify does it, there must be a way, unless Discord directly communicates with Spotify's DB.

**Comment by purpl3F0x** [comment]
It's not someone's issue. It's an explicit agreement with Spotify and Discord to allow that type of integration.
For a normal app to display an image it needs to be available in the assets on the developers page aka the image will come directly from Discord.

**Comment by Pavel-Sushko** [comment]
Right, I see. And updating those assets every time for a specific playlist would be too heavy on resources, or is that just not a thing?

**Comment by purpl3F0x** [comment]
Not a thing updating them. You need to upload them manually. Also there is a limit of 200. There are 70million songs 💩💩

**Comment by Minecon724** [comment]
it is possible to update them automatically, see https://github.com/Kaufi-Jonas/NowPlaying-for-TIDAL/issues/2#issuecomment-811988652
users will need to create their own app but its not a hard task
btw sorry for necroposting

**Comment by purpl3F0x** [comment]
Here is the thing, there is an asset limit of 300. The solution is kinda hacky. I don't know how many people are using the app - but latest version has 1.8K downloads at the time of writing so I think it might be a castle made out of sand writing that code

**Comment by Minecon724** [comment]
as i said before, users can create their own rpc app, its not that hard

**Comment by obeeblue** [comment]
> That's not possible by the Discord RPC API. You can only have a limited amount of assets. Spotify has some sort of deal with discord, even the images are from Spotify CDN and not Discords.
> 
> Same goes for the name. The name is set and only one per app id.
> 
> Closing the issue.

Is now

**Comment by 1nikolas** [comment]
There is an actual solution. Credits to this guy https://github.com/Mastermindzh/tidal-hifi/pull/84
Apparently you can set `largeImageKey` to a URL (instead of an uploaded asset name). It's undocumented but it works.

Discord proxies the images and the URL loaded on Discord looks like this `https://media.discordapp.net/external/c78dDCeR1nLDcfVlaxW7s1AzhrdPqhOIbIxjtv0zJw8/https/resources.tidal.com/images/99baaa31/52a0/40ee/a8d0/4525fb5f8a02/640x640.jpg`

**Comment by ShuriZma** [comment]
![image](https://user-images.githubusercontent.com/37740617/210108650-b77a81cc-3281-4d68-826a-2377c4524047.png)
Can definitely confirm its working
At the top you can see the rpc from this repo and at the bottom you can see my private one that ive been working on since yesterday

You can set external images for both, `largeImageKey` and `smallImageKey` and they dont use up any asset slots

**Comment by purpl3F0x** [comment]
Will push an update when I can. Or if anyone wants to push a commit...

**Comment by obeeblue** [comment]
omg yess please ;w;

**Comment by purpl3F0x** [comment]
Up on lastest release
