### ISSUE TITLE
Play on tidal button (Feature request)

### ISSUE THREAD

**Issue by SimDoes** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#56]
With discord rpc it's possible to add buttons as well. (Example [here](https://github.com/ThatOneCalculator/DiscordRPCMaker))

A suggestion would be to add a button that takes you to the track link (e.g. "Play on Tidal").

This feature is already implemented in another project [here](https://aur.archlinux.org/packages/tidal-hifi/).

**Comment by purpl3F0x** [comment]
Actually I have implemented that, but I never figured out how to register my application to discord to enable this feature

**Comment by ShuriZma** [comment]
I think the problem here is that youre using the discord game sdk. I made my own rpc in node js using the discordjs rpc and some tidal api package and there you can either register your application and use "Join" buttons etc via secrets OR just set the buttons. as far as i could see you cant make these plain buttons using the discord game sdk anymore. well atleast thats what seems to be everyones problem
