### ISSUE TITLE
Won't connect to TIDAL on MacOS Catalina

### ISSUE THREAD

**Issue by grummycodez** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#7]
Heya, I can't seem to get TIDAL to connect to the RPC client. Is this a known bug, or am I doing something wrong?

**Comment by purpl3F0x** [comment]
I don't have a Mac to test this. It was reported before that Catalina has a problem, probably due to the fact that the app need to be signed.
 I don't know if it was an actual issue or not. Discord sometimes is bit cocky to show RPC for a day or so. It would be good if you could build an executable yourself.

**Comment by grummycodez** [comment]
Already tried that, and it had the same problem

**Comment by purpl3F0x** [comment]
I see if I can do something from a VM n report back tomorrow

**Comment by purpl3F0x** [comment]
Yep that seems to be an issue. Although the issue isn't that the app doesn't connect to Discord. (There is is a small bug on line I attach bellow, this should be on scope forward, outisd of the if).

The actual issue here is the Tidal app (/ Catalina) where the window of the app now doesn't change title accordinging to what is playing. Tbh I seems it cant get even any window title, it returns a null pointer... 

I will see what it's doing on the Mojave VM, if its tidal app or osx version...

https://github.com/purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL/blob/e3c7c62193d569aab50c2627a0492c2f235fa181/osx_api_hook.hh#L75

**Comment by purpl3F0x** [comment]
Ok I identified the issue. It seems that from Catalina you need special permissions for to get the window titles (from another repo: https://github.com/lwouis/alt-tab-macos/issues/29). I'm not sure how I can solve this since the rpc is a simple c++ app.
My OSX-SDK knowledge is non existent so if anyone knows something would be appreciated

**Comment by purpl3F0x** [comment]
probably same thing happening on issue #2
