### ISSUE TITLE
Song time doesn't sync when the app is started mid-song.

### ISSUE THREAD

**Issue by EsserGaming** [purpl3F0x/TIDAL-Discord-Rich-Presence-UNOFFICIAL#92]
When I am playing a song and then I open the app it starts the timer at the beginning instead of at the time where the song I'm playing is at. 

I'm assuming this is because there isn't a way to tell at which second the song I'm listening to is at?

**Comment by ShuriZma** [comment]
last time i checked this rpc only read the track title etc from the window title and ran an api query with these. So yea it doesn't really know at which point you started listening to it or if you skiped/went back or whatever. Even if you'd be reading tidals traffic you wouldnt be able to properly determine that. you only know that the user started listening to a specific track, thats all. 

(as for the api approach you might not even know exactly which track is being played right now, since the tidal app makes a request for the next track usually ~30s before its being played. might be even more inaccurate)

**Comment by EsserGaming** [comment]
Interesting.. Though I wonder if there's a way to use Windows' media API instead, since I know a few applications that use it like VRChat OSC applications and whatnot.. Maybe there's a way to use that in tandem with the Tidal API?

**Comment by purpl3F0x** [comment]
Only way doing that would be with a dll injection I think
